const GET_USER_LISTS_REQUEST = 'GET_USER_LISTS_REQUEST';
const GET_USER_LISTS_SUCCESS = 'GET_USER_LISTS_SUCCESS';
const NAVIGATE_TO_USER_DETAILS = 'NAVIGATE_TO_USER_DETAILS';
const SELECT_USER = 'SELECT_USER';
const GET_USER_AVATAR_REQUEST = 'GET_USER_AVATAR_REQUEST';
const GET_USER_AVATAR_SUCCESS = 'GET_USER_AVATAR_SUCCESS';

export {
    GET_USER_LISTS_REQUEST,
    GET_USER_LISTS_SUCCESS,
    NAVIGATE_TO_USER_DETAILS,
    SELECT_USER,
    GET_USER_AVATAR_REQUEST,
    GET_USER_AVATAR_SUCCESS,
}